- name: Check compability with shell script
  hosts: all
  gather_facts: yes
  
  tasks:
  - name: Check hostname
    shell: echo "Hostname= " | tr -d "\n" | hostname && echo " OS= " | tr -d "\n" && uname -a  | cut -d ' ' -f 1
    register: result
  - local_action:
      copy
      content= {{ result }}
      dest= /home/jmanoarta
 
