- name: Check compability with shell script
  hosts: all
  gather_facts: yes
  
  tasks:
  - name: Check hostname
    shell:  uname -a | cut -d ' ' -f 2 && echo "OS:" && uname -a  | cut -d ' ' -f 1 >> test.txt
 
